# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20160527_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='photo',
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=10),
        ),
        migrations.AddField(
            model_name='photo_album',
            name='album_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog'),
        ),
    ]
