# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20160527_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='')),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo_album',
            name='album_name',
        ),
        migrations.DeleteModel(
            name='Photo_Album',
        ),
    ]
