# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:32
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20160527_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=stdimage.models.StdImageField(blank=True, upload_to=''),
        ),
    ]
