# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20160527_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image_file', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
