# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_auto_20160601_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_file',
            new_name='photo_img',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='cropping',
        ),
    ]
