# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_auto_20160601_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='colors',
            new_name='colour',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='day_in',
        ),
        migrations.AddField(
            model_name='dog',
            name='hair',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='id_number',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='mixed_race',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='race',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Very Large')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='tail',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
