# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_auto_20160717_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='id_number',
            new_name='number',
        ),
    ]
