# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_auto_20160717_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='hair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='tail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
