# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_auto_20160717_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra large', 'Very Large')], max_length=20),
        ),
    ]
