# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_auto_20160717_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
