# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0013_dog_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='race',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('Pequeno Porte', 'Pequeno Porte'), ('Médio Porte', 'Médio Porte'), ('Grande Porte', 'Grande Porte'), ('Muito Grande Porte', 'Muito Grande Porte')], max_length=20),
        ),
    ]
