# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0015_photo_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10),
        ),
    ]
